#!/bin/sh

ACTION="custompart-google-chrome-browser_${1}"

# mount point path
MP=$(get custom_partition.mountpoint)
# custom partition path
CP="${MP}/google-chrome-browser"
# output to systemlog with ID amd tag
LOGGER="logger -it ${ACTION}"

echo "Starting" | $LOGGER

case "$1" in
init)
	# Initial permissions
	chown -R 0:0 "${CP}" | $LOGGER
	chmod 755 "${MP}" | $LOGGER

	# Create user configuration and set permissions
	mkdir -p /userhome/.config
	chown -R user:users ${CP}/userhome /userhome/.config
	
	# Linking files and folders on proper path
	find "${CP}" | while read LINE
	do
		DEST=$(echo -n "${LINE}" | sed -e "s|${CP}||g")
		if [ ! -z "${DEST}" -a ! -e "${DEST}" ]; then
			# Remove the last slash, if it is a dir
			[ -d $LINE ] && DEST=$(echo "${DEST}" | sed -e "s/\/$//g") | $LOGGER
			if [ ! -z "${DEST}" ]; then
				ln -sv "${LINE}" "${DEST}" | $LOGGER
			fi
		fi
	done

	# fix mime types
	sed -i -e 's^firefox^google-chrome^g' /usr/share/applications/defaults.list 2>/dev/null
	sed -i -e 's^firefox^google-chrome^g' /usr/share/applications/mimeapps.list 2>/dev/null
	sed -i -e 's^firefox^google-chrome^g' /etc/xdg/xfce4/helpers.rc 2>/dev/null
	cp "$CP/usr/share/applications/google-chrome.desktop" /usr/share/applications 2>/dev/null
	cp "$CP/usr/share/applications/google-chrome.desktop" /usr/share/applications.mime 2>/dev/null
	
	# fix permissions
	chmod 4755 "$CP/opt/google/chrome/chrome-sandbox"

	# link policies directory contents
	[ -d /wfs/chrome/policies/managed ] && ln -sf /wfs/chrome/policies/managed/* /etc/opt/chrome/policies/managed/
	[ -d /wfs/chrome/policies/recommended ] && ln -sf /wfs/chrome/policies/recommended/* /etc/opt/chrome/policies/recommended/

	# create Downloads directory
	mkdir /userhome/Downloads 2>/dev/null
	chown user:users /userhome/Downloads
;;
stop)
	killall chrome
	sleep 3
;;
esac

echo "Finished" | $LOGGER

exit 0
